variables:
  IMAGE_BLUEPRINT: $CONTAINER_REGISTRY_PATH/blueprint

before_script:
  - docker login -u $CONTAINER_REGISTRY_USER -p $CONTAINER_REGISTRY_PASS $CONTAINER_REGISTRY_HOST

Build Blueprint:
  stage: build
  script:
    - docker pull $IMAGE_BLUEPRINT:latest || true
    - docker build --cache-from $IMAGE_BLUEPRINT:latest -f Dockerfile -t $IMAGE_BLUEPRINT:latest .
    - docker push $IMAGE_BLUEPRINT:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - ml-cluster-ci

Deploy Blueprint:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml --with-registry-auth blueprint
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - ml-cluster-ci

ETL Job:
  stage: .post
  before_script:
    - docker volume create blueprint-etl-job-vol
    - >
      docker run -d --rm --name blueprint-etl-job
      -v blueprint-etl-job-vol:/jobs
      --network gitlab-net
      -e DB_HOST=$DB_HOST
      -e DB_PORT=$DB_PORT
      -e DB_NAME=$DB_NAME
      -e DB_USER=$DB_USER
      -e DB_PASS=$DB_PASS
      -e REDIS_HOST=$REDIS_HOST_IN_GITLAB_NET
      -e REDIS_PORT=$REDIS_PORT
      -e REDIS_PASS=$REDIS_PASS
      -e REDIS_DB=$REDIS_DB
      $CONTAINER_REGISTRY_PATH/etl-base-image:latest tail -f /dev/null
    - docker cp jobs/etl.py blueprint-etl-job:/jobs/
  script:
    - docker exec blueprint-etl-job python /jobs/etl.py
  after_script:
    - docker stop blueprint-etl-job
    - docker volume rm blueprint-etl-job-vol
    - >
      export https_proxy=http://192.168.100.130:8888/ &&
      export http_proxy=http://192.168.100.130:8888/ &&
      apk add --update curl &&
      rm -rf /var/cache/apk/*
    - >
      curl -X POST "$SKYPE_BOT_URL"
      -H "accept: application/json" -H "Content-Type: application/json"
      -d "{\"msg\": \"Notif:\n‌Blueprint ETL job is done at $CI_JOB_STARTED_AT (UTC).\nStatus: $CI_JOB_STATUS\nPipeline source: $CI_PIPELINE_SOURCE\nSee logs on $CI_JOB_URL\"}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
      allow_failure: true
  tags:
    - etl-job